name: hi_panda
description: A new Flutter project.

publish_to: 'none'

version: 1.1.0+10

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4

  #api service
  http: ^0.13.4

  #modeling
  equatable: ^2.0.3

  #map
  google_maps_flutter: ^2.1.4

  #loading text
  skeleton_text: ^3.0.0
  #cache image
  cached_network_image: ^3.2.1

  #todo update this
  dots_indicator: ^2.1.0

  package_info: ^2.0.2
  #Slider
  carousel_slider: ^4.1.1
  #bottom Navigation
  curved_navigation_bar: ^1.0.3

  image_picker: ^0.8.4+4

  #numberPicker
  numberpicker: ^2.1.1

  #state Manager
  get: ^4.6.5
  get_storage: ^2.0.3



  #charts
  fl_chart: ^0.50.6
  #animation files
  lottie: ^1.3.0
  #show rate or submit rate
  flutter_rating_bar: ^4.0.0

  #caching
  shared_preferences: ^2.0.15
  smooth_page_indicator: ^1.0.0+2
  #intro
  introduction_screen: ^2.1.0
  #check network
  connectivity_plus: ^2.2.0


  #verify code
  flutter_verification_code: ^1.1.2+1
  #Sign in google
  google_sign_in: ^5.2.3
  google_sign_in_web: ^0.10.0+4
  #location
  geolocator: ^8.2.1
  #permission
  permission_handler: ^9.1.0
  modal_bottom_sheet: ^2.0.1

  #NavigationBar
  flutter_snake_navigationbar: ^0.6.1

  url_launcher: ^6.1.2
  #add file
  # file_picker: ^4.5.0
  #dataBase
  hive: ^2.0.6
  hive_flutter: ^1.1.0

  path_provider: ^2.0.9

  image_cropper: ^3.0.0

  #notifaction managers
  firebase_messaging: ^11.4.0
  android_alarm_manager_plus: ^2.0.5
  flutter_local_notifications: ^9.5.3+1

  #voice record
  audio_session: ^0.1.6+1
  audioplayers: ^0.20.1

  flutter_countdown_timer: ^4.1.0

  flutter_switch: ^0.3.2

  tutorial_coach_mark: ^1.2.3

  #image SVG
  flutter_svg: ^1.1.1+1

  flutter_audio_waveforms: ^1.2.1+6

  voice_message_package: ^0.0.74

  signalr_core: ^1.1.1

  flip_card: ^0.6.0

  palette_generator: ^0.3.3+1



  flutter_chat_bubble: ^2.0.0
  # Audio related
  audiotagger: ^2.2.1
  audio_service: ^0.18.1
  just_audio: ^0.9.28
  on_audio_query: ^2.5.0


  chewie: ^1.2.2
  video_player: ^2.2.9

  file_picker: ^5.0.1

  record: ^4.3.3

  video_thumbnail_imageview: ^0.0.5

  dropdown_button2: ^1.6.2

  device_info_plus: ^4.1.2

  flutter_html: any

  share_plus: ^4.4.0

  webview_flutter: ^3.0.4

  assets_audio_player: ^3.0.6

  percent_indicator: ^4.2.2

  slide_countdown: ^0.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^1.1.0
  build_runner: ^2.0.6

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/
    - assets/lottie/
    - assets/audios/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Dana
      fonts:
        - asset: assets/fonts/Dana-FaNum-Bold.ttf
        - asset: assets/fonts/Dana-FaNum-Light.ttf
        - asset: assets/fonts/Dana-FaNum-Medium.ttf
        - asset: assets/fonts/Dana-FaNum-Regular.ttf
    - family: yekan
      fonts:
        - asset: assets/fonts/IRANYekanLightMobile(FaNum).ttf
        - asset: assets/fonts/IRANYekanMobileBold(FaNum).ttf
        - asset: assets/fonts/IRANYekanRegularMobile(FaNum).ttf
    - family: IranSANS
      fonts:
        - asset: assets/fonts/irsans-b.ttf
        - asset: assets/fonts/irsans-m.ttf
        - asset: assets/fonts/irsans.ttf
    # - family: yekan
    #   fonts:
    #     - asset: assets/fonts/Yekan.ttf


